#!/bin/sh

basepath="/proc/device-tree"
device_name="$(cat "$basepath/model")"

if [ -n "$1" ];then

wifi down
case $1 in
apsta)
	uci set wireless.radio0.disabled='0'
	uci set wireless.ap0=wifi-iface
	uci set wireless.ap0.device='radio0'
	uci set wireless.ap0.network='lan'
	uci set wireless.ap0.mode='ap'                                               
	uci set wireless.ap0.ssid="KITEDTU"
	uci set wireless.ap0.encryption='none'

	uci set wireless.sta0=wifi-iface
	uci set wireless.sta0.device='radio0'
	uci set wireless.sta0.mode='sta'
	uci set wireless.sta0.network='wwan'

	uci set network.wwan=interface
	uci set network.wwan.proto='dhcp'
	if [ -n "$2" ];then
		uci set wireless.sta0.ssid="$2"
		if [ -n "$3" ];then
			uci set wireless.sta0.key="$3"
		else
			uci delete wireless.sta0.key
			uci set wireless.sta0.encryption='none'
		fi
	fi
	uci commit
	/etc/init.d/network restart
	;;
sta)
	uci set wireless.sta0=wifi-iface
	uci set wireless.sta0.device='radio0'
	uci set wireless.sta0.mode='sta'
	uci set wireless.sta0.network='wwan'
	uci set wireless.radio0.disabled='0'
	uci set wireless.ap0.disabled=1
	uci set wireless.sta0.disabled=0
	if [ -n "$4" ]; then
        uci set wireless.sta0.encryption="$4"
	else
        uci set wireless.sta0.encryption='psk'
	fi
	if [ -n "$2" ];then
		uci set wireless.sta0.ssid="$2"
		if [ -n "$3" ];then
			uci set wireless.sta0.key="$3"
		else
			uci delete wireless.sta0.key
		fi
	fi

	uci set network.wwan=interface
	uci set network.wwan.proto='dhcp'
	uci commit
	/etc/init.d/network restart
	;;
ap)
	uci set wireless.radio0.disabled='0'
	uci set wireless.sta0.disabled=1
	uci set wireless.ap0.disabled=0

	uci set network.wwan=interface
	uci set network.wwan.proto='dhcp'
	uci commit
	/etc/init.d/network restart
	;;
*)
	echo "Usage:"
	echo "	wifimode apsta/sta/ap <ssid> <key>"
	echo "e.g.	wifimode apsta 	[ssid] [key]"
	echo "		wifimode sta 	[ssid] [key]"
	echo "		wifimode ap"
esac
#wifi up
fi

