#!/bin/sh /etc/rc.common
USE_PROCD=1

START=99
STOP=92

start_service() {
        procd_open_instance
        procd_set_param command /bin/kitedtu 2>&1 >> /dev/null
        procd_set_param respawn 0
        procd_close_instance
}

stop_service() {
  killall -9 kitedtu
}

